language: python

env:
  global:
    # So we have acccess to the aws command.
    - PATH=$HOME/virtualenv/python2.7/bin:$PATH

before_install: echo "no-op"

install:
  - pip install awscli

before_script: echo "no-op"

script: echo "no-op"

before_deploy: echo "no-op"

deploy:
  provider: script
  script: cd literate && scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master

after_deploy: echo "no-op"

after_script: echo "no-op"

notifications:
  email: false
