language: python

env:
  global:
    # So we have acccess to the aws command.
    - PATH=$HOME/virtualenv/python2.7/bin:$PATH

install:
  - pip install awscli

script:
  # no-op

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
