# .zshenv is sourced on all invocations of the shell, unless the -f
# option is set. It should contain commands to set the command search
# path, plus other important environment variables. `.zshenv' should
# not contain commands that produce output or assume the shell is
# attached to a tty.

export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.zsh
export ZSH_THEME="hartmann"
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

export DOTFILES_HOME="$HOME/dev/personal/dotfiles"

# Used in some of my git-related scripts.
export DEFAULT_PR_BRANCH="staging"

# Use emacs as the default editor. It expects that an emacs daemon is
# running with the name 'shell-emacs'.
export EDITOR="emacsclient -c --socket-name=shell-emacs"

# Path.
#   For many of these path updates it would've been nicer to use
#   (brew --prefix <package>) to find the path, however, it's rather
#   slow so when you have a lot of them your boot time gets slow :(

# Coming from bash, I expect these to be in the PATH.
export PATH=/usr/local/bin:$HOME/bin:$PATH

# Make sure my shell scripts are on on the path
export PATH="$DOTFILES_HOME/bin:$PATH"

# Make sure that the homebrew installed emacs comes first in the
# shell.
export PATH="/usr/local/opt/emacs/bin:$PATH"

# fzf is an extremely useful tool.
# These are just some tweaks to make it even more useful than what
# the defaults are.
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--height 100% --reverse --color=bg+:#000000,hl:#EAC170,hl+:#EAC170,prompt:#EAC170,pointer:#EAC170"
