# .zshrc is sourced in interactive shells. It should contain
# commands to set up aliases, functions, options, key bindings, etc.

plugins=(
  # Plugins from oh-my-zsh
  git
  npm
  docker
  hub
  zsh-syntax-highlighting
  zsh_reload
  # My own plugins
  project
  aws-switch
  git-pr
)

source $ZSH/oh-my-zsh.sh

# Nice small convenience key-bindings.
# CTRL+T to select a file in the current directory and paste it.
# CTRL+R to get a nicer backwards history search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

### Tools

# AWS completions
source /usr/local/opt/awscli/libexec/bin/aws_zsh_completer.sh
