version: 2

jobs:
  build:
    working_directory: /home/babel/dotfiles
    docker:
      - image: mads379/dotfiles-ci:0.0.2
    steps:
      - checkout
      - run:
          name: Build
          command:
            cd literate && emacs --batch --script etc/project.el --eval "(org-publish-project \"everything\" t)"
      - run:
          name: Deploy
          command: |
            cd literate && ./scripts/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
