version: 2

jobs:
  build:
    working_directory: /home/babel/dotfiles
    docker:
      - image: mads379/dotfiles-ci:0.0.3
    steps:
      - checkout
      - run:
          name: Build
          command: make all
      - run:
          name: Deploy
          command: ./scripts/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - build
      - build:
          filters:
            branches:
              only:
                - master
