cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/php'
tap 'lampepfl/brew'

cask 'java'
brew 'sbt'
brew 'dotty'

brew 'ruby'
brew 'node@8'
brew 'python'
brew 'go'
brew 'opam'

brew 'php70'
brew 'php70-mcrypt'
brew 'php70-redis'
brew 'php70-xdebug'
brew 'homebrew/php/composer'

brew 'postgresql'
brew 'mysql'
brew 'redis'

brew 'zsh'
brew 'zsh-completions'

brew 'jq'
brew 'coreutils'
brew 'git'
brew 'ispell'
brew 'shellcheck'
brew 'cloc'
brew 'fswatch'
brew 'awscli'
brew 'fzf'
brew 'unrar'
brew 'ag'
brew 'ctags'

# Cute little tool that looks up cheatsheet information.
# e.g. cheat tar
# https://github.com/chrisallenlane/cheat
brew 'cheat'

# A handy little tool for displaying a folder structure like a tree.
# Example: tree -L 3
brew 'tree'

cask 'keybase'
cask 'alfred'
cask 'emacs'
cask 'sequel-pro'
cask 'iterm2'
cask '1password'
cask 'google-chrome'
cask 'slack'
cask 'transmission'
cask 'spotify'
cask 'appzapper'
cask 'flux'
cask 'skype'
cask 'postman'
cask 'docker'
cask 'visual-studio-code'
cask 'soulver'
cask 'spectacle'
cask 'beamer'
cask 'vlc'
cask 'virtualbox'

# Quick look plugins
# Syntax highlighting
cask 'qlcolorcode'
# Show files without extensions as plaintext
cask 'qlstephen'
# Render markdown rather than showing it as text
cask 'qlmarkdown'
# Pretty-printing and highlighting json
cask 'quicklook-json'
# Preview .patch files
cask 'qlprettypatch'
# Preview csv files
cask 'quicklook-csv'
# Show image size and resolution when display images
cask 'qlimagesize'
